<?php
namespace TasksApp;

/**
 * Class Pager.
 * @package TasksApp
 */
class Pager
{
    /** @var int  Total number of elements. */
    private $total;

    /** @var int  Number of elements per page. */
    private $elementsPerPage;

    /** @var string  Get parameter corresponding for page navigation. */
    private $getParameter;

    /**
     * Paginator constructor.
     * @param string $what What type of elements we are paginating corresponding to table name in DB.
     * @param int $elementsPerPage Number of elements per page.
     * @param string $getParameter Get parameter corresponding for page navigation.
     */
    public function __construct($what, $elementsPerPage, $getParameter)
    {
        $res = mysqli_fetch_row(mysqli_query(DBConnection::get(),
            "SELECT COUNT(id) FROM " . $what));
        $this->total = $res[0];
        $this->elementsPerPage = $elementsPerPage;
        $this->getParameter = $getParameter;
    }

    /**
     * Returns number of pages generated by paginator.
     * @return int  Number of pages generated by paginator.
     */
    public function getNumberOfPages()
    {
        return ceil((float)$this->total / (float)$this->elementsPerPage);
    }

    /**
     * Returns current page that user is working on.
     * @return int  Current page that user is working on.
     */
    public function getCurrentPage()
    {
        return (int)$_GET[$this->getParameter];
    }

    /**
     * Returns number of elements per page.
     * @return int  Number of elements per page.
     */
    public function getElementsPerPage()
    {
        return $this->elementsPerPage;
    }

    /**
     * @param string $controller  Controller name.
     * @param int $page  Page number.
     */
    public function printPage($controller, $page)
    {
        if ($page == $this->getCurrentPage()) {
            echo ($page + 1);
        } else {
            echo '<a href="/index.php?method=' . $controller
                . '&' . $this->getParameter . '=' . $page . '&sortBy='
            . (isset($_GET["sortBy"]) ? $_GET["sortBy"] : "id") . '">' . ($page + 1) . '</a>';
        }
    }
}